Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: true

Style/ExtraSpacing:
  Enabled: true
