Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 85
  
Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
