# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df29bab9840aaee70e7250fec82aae1588c13db2d3c26f79272129e2ba3d627aaa722adf5a838f2829db8c0a2fcd86b6a566bbae92b89c26fb1e623f2f327852

test:
  secret_key_base: 2ea89edaea753ab8e93cc4811bf6f9a0f7d30cc7b459df7a702e8673f945a10a797fc562f98232e3c6356759781f65edcb3229105e8857e5938060887dc51fe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
